# Welcome to Jekyll!

# Basic Site Settings
locale                   : "en-US"
title                    : "Preshanth Adhini Ramesh - Data Analyst"
title_separator          : "-"
name                     : &name "Preshanth Adhini Ramesh"
description              : &description "Experienced Data Analyst with a strong focus on healthcare analytics, leveraging extensive experience with AWS, Power BI, and data-driven decision making to enhance operational efficiency."
url                      : "https://academicpages.github.io" # the base hostname & protocol for your site
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "academicpages/academicpages.github.io"

# Site Author
author:
  avatar                 : "clock.png"
  name                   : "Preshanth Adhini Ramesh"
  bio                    : "Specializing in data analytics within the healthcare sector. Experienced in AWS Redshift, Power BI, and predictive modeling for patient care improvement."
  location               : "Boston, MA"
  employer               : "Northeastern University"
  email                  : "preshanth.adhini.ramesh@gmail.com"
  linkedin               : "linkedin.com/in/preshanthar"
  github                 : "github.com/Preshupj"

# Social Media
twitter                  : "your_twitter_username"
linkedin                 : "preshanthar"
github                   : "Preshupj"

# SEO Related
google_site_verification : "your_google_site_verification_code"
bing_site_verification   : "your_bing_site_verification_code"

# Analytics
analytics:
  provider               : "google" # Enable Google Analytics
  google:
    tracking_id          : "your_google_analytics_tracking_id"

# Social Sharing
og_image                 : "clock.png" # Default Open Graph/Twitter image

# Collections
collections:
  portfolio:
    output              : true
    permalink           : /portfolio/:path/

# Outputting
permalink                : /:categories/:title/
timezone                 : "America/New_York" # Updated to your time zone

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
